project_id = "dijdhvewjozrycjqwoqs"

[functions.generate-description]
verify_jwt = false

[functions.ai-copilot]
verify_jwt = true

[functions.ai-insights]
verify_jwt = true

[functions.ai-daily-brief]
verify_jwt = false

[functions.showcase-chat]
verify_jwt = false
